//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dummy
    {
        public int dummyid { get; set; }
        public string dummyname { get; set; }
        public Nullable<int> dummyage { get; set; }
    }
}
